# macOS half of setup.sh. Sourced by setup/setup.sh when ~/.config/host says
# "macos"; $REPO_DIR, $HOST and report_line() come from there.

HOST_PM=brew

host_pkg() {
  case "$1" in
    cc)          echo gcc ;;
    rg)          echo ripgrep ;;
    nvim)        echo neovim ;;
    # brew splits the CLI out of the 'tree-sitter' formula.
    tree-sitter) echo tree-sitter-cli ;;
    alacritty)   echo cask:alacritty ;;
    *)           echo "$1" ;;
  esac
}

host_install() {
  for pkg in "$@"; do
    if [[ "$pkg" == cask:* ]]; then
      brew install --cask "${pkg#cask:}"
    else
      brew install "$pkg"
    fi
  done
}

host_checks() {
  if command -v pbcopy >/dev/null 2>&1; then
    report_line clipboard ok "'\"+y' clipboard yank in nvim (pbcopy)"
  else
    report_line clipboard "MISSING" "pbcopy is built into macOS -- something is wrong with PATH"
  fi

  if [ -d "/Applications/Karabiner-Elements.app" ]; then
    report_line karabiner ok "reads karabiner/karabiner.json"
  else
    report_line karabiner "MISSING" "brew install --cask karabiner-elements"
  fi
}

host_post() {
  # alacritty/alacritty.toml imports alacritty/local.toml, which is gitignored
  # because the fish path differs per machine. Generate it here if missing.
  #
  # This matters on macOS specifically: Alacritty launches $SHELL, and a GUI
  # app's $SHELL is frozen at login time -- running `chsh` doesn't reach it
  # until you log out. Naming the shell explicitly sidesteps that entirely.
  local alacritty_local="$REPO_DIR/alacritty/local.toml"
  [ -f "$alacritty_local" ] && return 0

  local fish_path
  if fish_path="$(command -v fish)"; then
    cat > "$alacritty_local" <<EOF
# Machine-local Alacritty overrides. NOT tracked in git -- generated by
# ../setup/macos-setup.sh, which fills in the fish path for this machine.

[terminal.shell]
program = "$fish_path"
args = ["--login"]
EOF
    echo
    echo "Generated alacritty/local.toml -> shell = $fish_path"
  else
    echo
    echo "fish not found; skipping alacritty/local.toml (Alacritty will fall back to \$SHELL)."
  fi
}
